# Constants
{{$NODES_PER_NAMESPACE := DefaultParam .NODES_PER_NAMESPACE .Nodes}}
{{$PODS_PER_NODE := DefaultParam .PODS_PER_NODE 10}}
{{$ENABLE_CHAOSMONKEY := false}}
{{$qps := DefaultParam .qps 10}}
{{$KUBEMARK := true}}

# kubectl get node -o json | jq -r ".items[].status.allocatable.cpu"
{{$NODE_FREE_CPU := DefaultParam .NODE_FREE_CPU 1}}
# kubectl get node -o json | jq -r ".items[].status.allocatable.memory"
# gets it in Ki - field is in MB
{{$NODE_FREE_MEM := DefaultParam .NODE_FREE_MEM 3840}}
# Variables
{{$namespaces := DivideInt .Nodes $NODES_PER_NAMESPACE}}
{{$podsPerNamespace := MultiplyInt $PODS_PER_NODE $NODES_PER_NAMESPACE}}
{{$totalPods := MultiplyInt $podsPerNamespace $namespaces}}
# Pod Resource Request
{{$POD_CPU_MILLI := DivideFloat $NODE_FREE_CPU (MultiplyFloat $PODS_PER_NODE .9)}}
{{$POD_MEMORY_MB := DivideFloat $NODE_FREE_MEM (MultiplyFloat $PODS_PER_NODE .9)}}

# Test Throughput Setup //TODO
{{$SCHEDULER_THROUGHPUT_THRESHOLD := DefaultParam .CL2_SCHEDULER_THROUGHPUT_THRESHOLD 0}}
{{$DENSITY_TEST_THROUGHPUT := DefaultParam .DENSITY_TEST_THROUGHPUT 100}}
{{$MIN_SATURATION_PODS_TIMEOUT := 180}}
{{$saturationDeploymentTimeout := DivideFloat $totalPods $DENSITY_TEST_THROUGHPUT | AddInt $MIN_SATURATION_PODS_TIMEOUT}}

# Methods that don't work
# APResponsiveness
# CPUProfile
# ETCD Metrics
# Memory Profile
# MetricsForE2E
# Scheduling Metrics
# OOM TrackingIt
# InClusterNetworkLatency
# DNSLookupLatency

name: Simple_Bring_Up
namespace:
  number: 1
tuningSets:
- name: Uniformqps
  qpsLoad:
    qps: {{$qps}}

steps:
- name: Starting Measurements
  measurements:
  - Identifier: ScaleUpTimer
    Method: Timer
    Params:
      action: start
      label: scale_up_time
  - Identifier: PodStartupLatency
    Method: PodStartupLatency
    Params:
      action: start
      labelSelector: group = nichotr
      threshold: 1h
  {{if not $KUBEMARK}}
  - Identifier: ResourceUsageSummary
    Method: ResourceUsageSummary
    Params:
      action: start
  {{end}}
  - Identifier: SchedulingThroughput
    Method: SchedulingThroughput
    Params:
      action: start

- name: Creating saturation pods
  phases:
    - namespaceRange:
        min: 1
        max: 1
      replicasPerNamespace: 1
      tuningSet: Uniformqps
      objectBundle:
        - basename: deployment
          objectTemplatePath: deployment.yaml
          templateFillMap:
            Replicas: {{$podsPerNamespace}}
            Group: nichotr
            CpuRequest: {{$POD_CPU_MILLI}}m
            MemoryRequest: {{$POD_MEMORY_MB}}M

- name: Collecting pod measurements
- measurements:
    - Identifier: WaitingForPods
      Method: WaitForRunningPods
      Params:
        labelSelector: group = nichotr
        desiredPodCount: {{$totalPods}}
        timeout: 1h

- name: Timing Separation For Scale Up
- measurements:
    - Identifier: ScaleUpTimer
      Method: Timer
      Params:
        action: stop
        label: scale_up_time
    - Identifier: ScaleDownTimer
      Method: Timer
      Params:
        action: start
        label: scale_down_time

- name: Deleting saturation pods
  phases:
    - namespaceRange:
        min: 1
        max: 1
      replicasPerNamespace: 0
      tuningSet: Uniformqps
      objectBundle:
        - basename: deployment
          objectTemplatePath: deployment.yaml

- name: Waiting for Deletion
- measurements:
    - Identifier: WaitingForPods
      Method: WaitForRunningPods
      Params:
        labelSelector: group = nichotr
        desiredPodCount: 0
        timeout: 1h

- name: Timing Separation for Scale Down
- measurements:
    - Identifier: ScaleDownTimer
      Method: Timer
      Params:
        action: stop
        label: scale_down_time
    - Identifier: PodStartupLatency
      Method: PodStartupLatency
      Params:
        action: gather
    {{if not $KUBEMARK}}
    - Identifier: ResourceUsageSummary
      Method: ResourceUsageSummary
      Params:
        action: gather
    {{end}}
    - Identifier: SchedulingThroughput
      Method: SchedulingThroughput
      Params:
        action: gather
